# Generated by Django 4.1.6 on 2023-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49, verbose_name='Имя')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
